### PR TITLE
Add progress bar to Ghidra script

### PR DESCRIPTION
**Pull request by tellowkrinkle**
Ghidra script processing takes a long time so having a progress bar is nice

### CODE REVIEW

**Comment by masagrator** [comment]
It could take less time, but from 6.3.0 version il2cppdumper deleted option to disable MakeFunction.

**Comment by therealchjones** [comment]
Works as expected. Very helpful for large program.

@masagrator, for the current project I'm working on, script.json is 58MB. All except the "Addresses" section completes in less than 2 minutes. "Addresses" (the part that calls make_function) takes several hours. If you don't wish to run that section, you can remove the "Addresses" entry in processFields at the top of the script; the additional flag in config.json isn't really necessary.

**Comment by therealchjones** [comment]
(And, FWIW, I may have found the cause of that delay. See #374 (and thanks to @masagrator's issue #229).)

**Comment by Perfare** [comment]
Very useful feature, thanks for the help.

**Pull request merged**
