### PR TITLE
i have added tuturial link how to find CodeRegistration and MetadataRegistration

### PR DESCRIPTION
**Pull request by morelli690**

### CODE REVIEW

**Comment by Perfare** [comment]
I am sorry I don't want to add any tutorials.
In addition, this tutorial is not a good example, it is only on the PC platform and may not work well due to compiler optimizations.

**Comment by morelli690** [comment]
I do know isnt for all platforms, just did that to help some ppl here which opened issue about it, well anyways its ok, if you want link my fork for opened issues about it ok XD

**Comment by morelli690** [comment]
i just solved issue number #183 with my tutorial, why not just especify that's only for PC platform, wouldn't hurt i promess.

**Comment by Perfare** [comment]
He just chose the wrong executable file.
Also, why not use the automatic mode?

**Comment by morelli690** [comment]
I do know that automatic should work, but didnt worked for Rust(facepunch), that's why i did the tutorial, + it also help people know what to do by looking the images i put there.

**Pull request closed without merging**
